Fix the bodyStartPos in the ParseSIPMessage Method
sipsorcery-org/sipsorcery pull request #832
Opened 2022-08-31 03:46 UTC by danch15

Fix the bodyStartPos in the ParseSIPMessage Method when the FromName or ToName is Chinese

2022-08-31 08:55 UTC, danch15 commented
#779 Call a number then cancel immediately, and then make an incoming call by other device, then answered. The SIPUserAgent.OnCallHungup Event was not triggered when hanging up.

2022-08-31 09:36 UTC, sipsorcery requested changes
Be great to see a unit test for this case.

2022-08-31 11:17 UTC, danch15 commented on src/core/SIP/SIPMessageBuffer.cs
> +                            var bodyStartPos = sipEncoding.GetByteCount(headerString) + sipEncoding.GetByteCount(sipMessage.FirstLine) + 2 + 4;
string sipFromName = “呼叫方名字”;

To: "被叫方名字" <sip:5030004203@172.17.3.4:5060>;tag=LKFBNRWYOU
From: "呼叫方名字" <sip:57660000@172.17.2.2>;tag=DTLKNZCUCG

I am sorry I forget the new '2', but it must exist, your just test it.

2022-09-01 06:26 UTC, danch15 commented
I don't wanna pull request of the "src/core/SIP/SIPMessageBuffer.cs" and "src/core/SIP/Channels/SIPUDPChannel.cs" files, I just comit it to my fork, I'm not familiar with GitHub, Sorry. How can I cancel the pull request of these two files?

2022-09-01 07:09 UTC, closed without merging

2022-09-01 12:29 UTC, danch15 commented
What the ???

2022-09-01 12:31 UTC, sipsorcery commented
> What the ???

Closed the PR because you didn't want it merged into this repo.

2022-09-16 03:19 UTC, danch15 commented
> > What the ???
> 
> Closed the PR because you didn't want it merged into this repo.

https://github.com/sipsorcery-org/sipsorcery/issues/848